Tournament format
ACMUCSP/arena-brawl-wiki pull request #12
Opened 2021-07-29 04:15 UTC by BasicAlgorithm

2021-07-30 14:28 UTC, rodp63 requested changes

2021-07-30 14:28 UTC, rodp63 commented on pages/event.md
>  #### Etapa semifinales
Usar `Clasificatorias` en lugar de `Semifinales`

2021-07-30 14:28 UTC, rodp63 commented on pages/event.md
> +  if (equipos > 10) return static_cast<int>(ceil(equipos/10));
🤣🤣 sin el `static_cast` creo que se entiende bien. basta con `return ceil(equipos/10)`

2021-07-30 14:28 UTC, rodp63 commented on pages/event.md
> +  return static_cast<int>(floor( 20 / (grupos * 2)));
Same here

2021-07-30 14:28 UTC, rodp63 commented on pages/event.md
> +  else exit (EXIT_FAILURE);
el `exit` no va, todos `ifs` me parece bien

2021-07-31 01:15 UTC, BasicAlgorithm commented on pages/event.md
> +  if (equipos > 10) return static_cast<int>(ceil(equipos/10));
Pondré double entonces, ya que ceil o floor retorna double. Para evitar el warning.

2021-08-02 20:29 UTC, rodp63 approved these changes

2021-08-02 20:29 UTC, merged

2021-08-03 03:22 UTC, rodp63 commented
👀